
sudo: required
services:
- docker
before_install:
- docker pull node:8-onbuild
- docker build -t probot-hello .
script:
- docker run --rm probot-hello npm run test
deploy:
  provider: heroku
  api_key:
    secure: t3t7jlPMScLYdZBvBXTOKSzD6D7hfmsg5dWVbetQuYCBDfhy0UYsMpsyxGuPkude7NBeafI22Fb7OeIjxUW9lMnUR0PFDaKDyYvGdNP7REyd1Dji8ZW8l/LZAQQnY4xGVRRnNleYlOTXdUTFsizdyzv3kxfFjucELGCXIHXbfQHUqKW5WSrl8HioidEGxJFFmdf/olteRXw+qJIfTxCYXnxm2n0BgnjOktNmqlpGTDOxdBUOj9UYVYOHm9tcmiXpG2tyFIz9JfS1CTnhiIofVD5N9IVNOrLe3XSKlh2HrnH8S9o+UIu5wCyak1y3qQshAGpUbAIuRAGveQbPtThGFcIeqYkQob1m8dgnCx9PrRFPt5hMQ/qULfL/Jx5IphGbctun8NQ4W/7mWgwvZWA/405/WILGYF1dFzbIZpmcpDRKqMcxFvEahGDsau+a5dN0i4gQ91RV+z5mj8KaYJNaGBs+Oi8nByjSZ+t7+X1JBWE743bJkXeTzFRonoO0y7XFDa3qgdUqCfCOQcRU/f9rNSj0TC5WIapRenR6A23kRBG2YmM4q/WyEn/wk8v2KBF3/A6xvg/UgPRuv6X/1o5hgonGAEt9eVhksyzPYtvAJF4hOgzQqhkGwtRhieng0PYvi09JaWPCitW313DkVtopRLlAnEloK+ynOHP1j93/VVE=
  on: heroku_production
  app: probot-borhen
