
sudo: required
services:
- docker
before_install:
- docker pull node:8-onbuild
- docker build -t probot-hello .
script:
- docker run --rm probot-hello npm run test
deploy:
  provider: heroku
  api_key:
    secure:
    n/lkuagNt3mC9ioyWbzalJp2eH4DLADkRTIsSjvIsNkTt1i7swVd86L7PR6wRI2RwiTJNj4tCOd1m3j51SIV/OcSwziqld89K81T8c5GCYxv440nsKcPh6QQcpH/pKkt17OE1GcUrDGhODF8g/G6O3yI0omaT9ev3Xto5BLN2UnEEKu8giZ3+3G4mGecA2OGpR+Af3PfC1z2eS3uIef1UVS0pajgMzv78NNBei7b/Li/hDFfEbiiNj4qJF1Rr/5G6j1J+QGHH8BCU7a2zug3vHYy701rDl5neXFxTIDiBMm1BKZCdDZgzdaz83tvFdhSc/52WZ9ayy1MzGp6/uwEVB0HyEIfaT6UL7xFDph904PZgW7uNxPQnBNj5pjycKWO01oqhg2p9gvjoh61Vmbg7dYrprhP/MmKPIXykfvTn4h2fcHPkEimKIEYBmbuygONfoAMWG5pXDXf5GDeqng6ptaPx5MbyaU1FgMKvvJaLU/Kw4BSjO8vzOmig3OPy516jsROLqBpJDkh849aMvOSpk5UdYHRIjy63SisTRm5ksX7DC7/G6Lz2Ub3GIreJ/E5eFn5yjk6BbjdHxQTKHGj+vXRhTWkiqldnlW/0/sykjVj8D+5x+wBYh5YHwiuMvYq/fUBleRyDQi4k2OFuyyn4HqmCtG+Zcr9HeE1V3wg5q4=
  on: heroku_production
  app: probot-borhen
