sudo: required
services:
  - docker

before_install:
  - docker pull node:8-onbuild

install:
  - docker build -t probot-hello .

script:
  - docker run --rm probot-hello npm run test
  - docker run --rm probot-hello -p 3000:3000 npm start
  - docker run --rm probot-hello npm run lint

after_success:
  - docker tag probot-hello probot-hello:$(git rev-parse HEAD)
